### ISSUE TITLE
Puddles.

### ISSUE THREAD

**Issue by RDKRACZ** [TeamMidnightDust/VisualOverhaul#8]
- They have weird placement when in a hand (yea so important)
![image](https://user-images.githubusercontent.com/43277609/111091975-edd6c100-8534-11eb-9b8a-cbeef3d95d7c.png)

- No config for disabling it but I'm okay with this
- I think they don't generate - I waited in a rain for two minutes and not a single one
- they have a collision?
![image](https://user-images.githubusercontent.com/43277609/111092091-545bdf00-8535-11eb-80e2-50e524788cfb.png)

**Comment by Motschen** [comment]
- Puddle items can't be accessed in survival mode. their purpose is just to show right in waila and as a debug item for testing puddles.
- Puddle generation can be disabled by setting the game rule "puddleSpawnRate" to 0
- Try setting puddleSpawnRate to 10 and see if that helps. I wanted to make puddles generate only rarely, because they can be quite annoying for some people.
- How did you even get a puddle floating in the air? I made it so if you break the block underneath they just disappear, so that also shouldn't be a problem as long as you aren't using any commands.

**Comment by RDKRACZ** [comment]
>How did you even get a puddle floating in the air?

Yes, I used the /setblock just to test collision.

>Try setting puddleSpawnRate to 10

Oh, so they do generate. 10 is fine considering that puddles can't spawn under trees so in forests they are rare even with 10.

>can be disabled by setting the game rule

You might want to give some information in the config about this.

Can you make them slowly disappear after some time after rain?

Also this
![image](https://user-images.githubusercontent.com/43277609/111132021-29937a00-8579-11eb-8ecf-e0116bff3453.png)
![image](https://user-images.githubusercontent.com/43277609/111132199-5778be80-8579-11eb-88cd-de2d9c1375f1.png)

**Comment by Motschen** [comment]
They already slowly disappear after rain

**Comment by Motschen** [comment]
Also, the connecting water thing is known, I'm currently looking into how to fix that. I hope it won't be too noticeable during normal gameplay

**Comment by Motschen** [comment]
The weird shapes should be fixed in the latest commit.
